### ISSUE TITLE
[BUG] - CDSDashboards permissions denied when sharing with additional users

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#1202] opened 2022-03-25 11:51 UTC
### OS system and architecture in which you are running QHub

Linux (will occur on any OS)

### Expected behavior

Should be able to share dashboards with other users.

### Actual behavior

503 permissions denied when attempting

### How to Reproduce the problem?

Share a dashboard

### Integrations

dashboards

**Comment by costrouc** [comment] 2022-03-29 18:40
@danlester do you have any ideas why when a dashboard is shared between users it fails? Is this due to using keycloak for the auth?

**Comment by viniciusdc** [comment] 2022-04-06 14:57
@danlester I was able to replicate this issue, except with being in the admin group every attempt to access the dashboard got me the error above

**Comment by danlester** [comment] 2022-04-07 12:06
To clarify, @viniciusdc attempt above is with JupyterHub 2.2.2 which has a separate problem - access is blocked by JupyterHub's RBAC.

For QHub 4.0, the problem is that it is blocked by jhsingle-native-proxy further downstream. I believe that is basically due to [dropping this code](https://github.com/Quansight/qhub/pull/627/files) in the big refactor recently.

**Comment by iameskild** [comment] 2022-04-10 05:58
Closed by #1237

**Closed by iameskild** 2022-04-10 05:58 UTC
Labels: type: bug 🐛, area: integration/dashboards
