### ISSUE TITLE
Scaling Dask Clusters with Multiple Users

### ISSUE THREAD

**Issue by dswillett** [Quansight/qhub#916] opened 2021-11-10 20:04 UTC
## Describe the bug

We launched a qhub instance on AWS and had multiple users login and try to spun up small dask clusters at the same time.  This crashed the whole EKS cluster multiple times.  :).  We are very new to qhub, so this could be a config error on our part, but we do not know where to go from here.  We also followed the instructions in the FAQs regarding the AZ balancing and that did not seem to resolve the issue.  

## Expected behaviour

We would expect many users to simultaneously scale dask clusters.  

## Actual behaviour

Scaling crashes the whole EKS cluster.  

## How to reproduce

qhub-config.yaml:
project_name: test-oasis
provider: aws
domain: xxxxxxxxxxxx
  type: self-signed
security:
  authentication:
    type: GitHub
    config:
      client_id: xxxxx
      client_secret: xxxxx
      oauth_callback_url: xxxx
  users:
    xxx:
      uid: 1000
      primary_group: admin
      secondary_groups:
      - users
    xxx:
      uid: 1001
      primary_group: admin
      secondary_groups:
      - users
    xx:
      uid: 1002
      primary_group: admin
      secondary_groups:
      - users
  groups:
    users:
      gid: 100
    admin:
      gid: 101
default_images:
  jupyterhub: quansight/qhub-jupyterhub:v0.3.13
  jupyterlab: quansight/qhub-jupyterlab:v0.3.13
  dask_worker: quansight/qhub-dask-worker:v0.3.13
  dask_gateway: quansight/qhub-dask-gateway:v0.3.13
  conda_store: quansight/qhub-conda-store:v0.3.13
storage:
  conda_store: 60Gi
  shared_filesystem: 100Gi
theme:
  jupyterhub:
    hub_title: QHub - test-oasis
    hub_subtitle: Autoscaling Compute Environment on Amazon Web Services
    welcome: Welcome to taheva.org. It is maintained by <a href="http://quansight.com">Quansight
      staff</a>. The hub's configuration is stored in a github repository based on
      <a href="https://github.com/Quansight/qhub/">https://github.com/Quansight/qhub/</a>.
      To provide feedback and report any technical problems, please use the <a href="https://github.com/Quansight/qhub/issues">github
      issue tracker</a>.
    logo: /hub/custom/images/jupyter_qhub_logo.svg
    primary_color: '#4f4173'
    secondary_color: '#957da6'
    accent_color: '#32C574'
    text_color: '#111111'
    h1_color: '#652e8e'
    h2_color: '#652e8e'
monitoring:
  enabled: true
cdsdashboards:
  enabled: true
  cds_hide_user_named_servers: true
  cds_hide_user_dashboard_servers: false
ci_cd:
  type: github-actions
  branch: main
terraform_state:
  type: remote
namespace: dev
amazon_web_services:
  region: us-west-2
  kubernetes_version: '1.18'
  node_groups:
    general:
      instance: m5.xlarge
      min_nodes: 1
      max_nodes: 3
    user:
      instance: m5.large
      min_nodes: 1
      max_nodes: 9
    worker:
      instance: m5.large
      min_nodes: 1
      max_nodes: 9
profiles:
  jupyterlab:
  - display_name: Small Instance
    description: Stable environment with 1 cpu / 4 GB ram
    default: true
    kubespawner_override:
      cpu_limit: 1
      cpu_guarantee: 0.75
      mem_limit: 4G
      mem_guarantee: 2.5G
      image: quansight/qhub-jupyterlab:v0.3.13
  - display_name: Medium Instance
    description: Stable environment with 2 cpu / 8 GB ram
    kubespawner_override:
      cpu_limit: 2
      cpu_guarantee: 1.5
      mem_limit: 8G
      mem_guarantee: 5G
      image: quansight/qhub-jupyterlab:v0.3.13
  dask_worker:
    Small Worker:
      worker_cores_limit: 1
      worker_cores: 0.75
      worker_memory_limit: 4G
      worker_memory: 2.5G
      worker_threads: 1
      image: quansight/qhub-dask-worker:v0.3.13
    Medium Worker:
      worker_cores_limit: 2
      worker_cores: 1.5
      worker_memory_limit: 8G
      worker_memory: 5G
      worker_threads: 2
      image: quansight/qhub-dask-worker:v0.3.13
   High  Worker:
      worker_cores_limit: 2
      worker_cores: 1.5
      worker_memory_limit: 10G
      worker_memory: 7G
      worker_threads: 2
      image: quansight/qhub-dask-worker:v0.3.13
environments:
  environment-dask.yaml:
    name: dask
    channels:
    - conda-forge
    dependencies:
    - python
    - ipykernel
    - ipywidgets
    - qhub-dask ==0.3.13
    - dask ==2021.09.1
    - dask.distributed ==2021.09.1
    - python-graphviz
    - numpy
    - numba
    - pandas
  environment-dashboard.yaml:
    name: dashboard
    channels:
    - conda-forge
    dependencies:
    - python==3.9.7
    - ipykernel==6.4.1
    - ipywidgets==7.6.5
    - qhub-dask==0.3.13
    - param==1.11.1
    - python-graphviz==0.17
    - matplotlib==3.4.3
    - panel==0.12.4
    - voila==0.2.16
    - streamlit==1.0.0
    - dash==2.0.0
    - cdsdashboards-singleuser==0.5.7

**Comment by iameskild** [comment] 2021-11-10 20:28
Hey @dswillett, thank you for your interest in QHub, I'm sorry to hear that you're experiencing issues. I will try to recreate this issue as soon as I can. In the meantime, would you mind answering some of these questions:
- Can a single user launch dask workers? If so, how many at a single time?
- Besides adding users and making minor changes to the `max_nodes`, are there any other changes that were made to the `qhub-config.yaml`? (it can be a little difficult to parse the config file when it's "[unformatted](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)" 😅)
- Being able to run through [this dask example](https://gist.github.com/iameskild/1a45cbd114595fa371d2d127448c5e33) is a good sign that things are working, would you mind giving it a try as well?

**Comment by dharhas** [comment] 2021-11-10 20:54
@dswillett can you attach the config.yaml file to a comment. You should be able to drag and drop.

**Comment by tylerpotts** [comment] 2021-11-10 21:37
```
qhub-config.yaml:
project_name: test-oasis
provider: aws
domain: xxxxxxxxxxxx
  type: self-signed
security:
  authentication:
    type: GitHub
    config:
      client_id: xxxxx
      client_secret: xxxxx
      oauth_callback_url: xxxx
  users:
    xxx:
      uid: 1000
      primary_group: admin
      secondary_groups:
      - users
    xxx:
      uid: 1001
      primary_group: admin
      secondary_groups:
      - users
    xx:
      uid: 1002
      primary_group: admin
      secondary_groups:
      - users
  groups:
    users:
      gid: 100
    admin:
      gid: 101
default_images:
  jupyterhub: quansight/qhub-jupyterhub:v0.3.13
  jupyterlab: quansight/qhub-jupyterlab:v0.3.13
  dask_worker: quansight/qhub-dask-worker:v0.3.13
  dask_gateway: quansight/qhub-dask-gateway:v0.3.13
  conda_store: quansight/qhub-conda-store:v0.3.13
storage:
  conda_store: 60Gi
  shared_filesystem: 100Gi
theme:
  jupyterhub:
    hub_title: QHub - test-oasis
    hub_subtitle: Autoscaling Compute Environment on Amazon Web Services
    welcome: Welcome to taheva.org. It is maintained by <a href="http://quansight.com">Quansight
      staff</a>. The hub's configuration is stored in a github repository based on
      <a href="https://github.com/Quansight/qhub/">https://github.com/Quansight/qhub/</a>.
      To provide feedback and report any technical problems, please use the <a href="https://github.com/Quansight/qhub/issues">github
      issue tracker</a>.
    logo: /hub/custom/images/jupyter_qhub_logo.svg
    primary_color: '#4f4173'
    secondary_color: '#957da6'
    accent_color: '#32C574'
    text_color: '#111111'
    h1_color: '#652e8e'
    h2_color: '#652e8e'
monitoring:
  enabled: true
cdsdashboards:
  enabled: true
  cds_hide_user_named_servers: true
  cds_hide_user_dashboard_servers: false
ci_cd:
  type: github-actions
  branch: main
terraform_state:
  type: remote
namespace: dev
amazon_web_services:
  region: us-west-2
  kubernetes_version: '1.18'
  node_groups:
    general:
      instance: m5.xlarge
      min_nodes: 1
      max_nodes: 3
    user:
      instance: m5.large
      min_nodes: 1
      max_nodes: 9
    worker:
      instance: m5.large
      min_nodes: 1
      max_nodes: 9
profiles:
  jupyterlab:
  - display_name: Small Instance
    description: Stable environment with 1 cpu / 4 GB ram
    default: true
    kubespawner_override:
      cpu_limit: 1
      cpu_guarantee: 0.75
      mem_limit: 4G
      mem_guarantee: 2.5G
      image: quansight/qhub-jupyterlab:v0.3.13
  - display_name: Medium Instance
    description: Stable environment with 2 cpu / 8 GB ram
    kubespawner_override:
      cpu_limit: 2
      cpu_guarantee: 1.5
      mem_limit: 8G
      mem_guarantee: 5G
      image: quansight/qhub-jupyterlab:v0.3.13
  dask_worker:
    Small Worker:
      worker_cores_limit: 1
      worker_cores: 0.75
      worker_memory_limit: 4G
      worker_memory: 2.5G
      worker_threads: 1
      image: quansight/qhub-dask-worker:v0.3.13
    Medium Worker:
      worker_cores_limit: 2
      worker_cores: 1.5
      worker_memory_limit: 8G
      worker_memory: 5G
      worker_threads: 2
      image: quansight/qhub-dask-worker:v0.3.13
   High  Worker:
      worker_cores_limit: 2
      worker_cores: 1.5
      worker_memory_limit: 10G
      worker_memory: 7G
      worker_threads: 2
      image: quansight/qhub-dask-worker:v0.3.13
environments:
  environment-dask.yaml:
    name: dask
    channels:
    - conda-forge
    dependencies:
    - python
    - ipykernel
    - ipywidgets
    - qhub-dask ==0.3.13
    - dask ==2021.09.1
    - dask.distributed ==2021.09.1
    - python-graphviz
    - numpy
    - numba
    - pandas
  environment-dashboard.yaml:
    name: dashboard
    channels:
    - conda-forge
    dependencies:
    - python==3.9.7
    - ipykernel==6.4.1
    - ipywidgets==7.6.5
    - qhub-dask==0.3.13
    - param==1.11.1
    - python-graphviz==0.17
    - matplotlib==3.4.3
    - panel==0.12.4
    - voila==0.2.16
    - streamlit==1.0.0
    - dash==2.0.0
    - cdsdashboards-singleuser==0.5.7
    ```
@iameskild Here's the above in code format for easier reading

**Comment by dharhas** [comment] 2021-11-10 21:39
`This crashed the whole EKS cluster multiple times`

This is concerning, why would launching a dask cluster take down the rest of the system?

**Comment by tylerpotts** [comment] 2021-11-10 21:41
:point_up: Could we have more details on how it crashed? Was it just the dask cluster or the entire QHub? How did you bring it back up?

**Comment by dswillett** [comment] 2021-11-10 21:41
@iameskild Should have caught that earlier. 

@tylerpotts and @dharhas Thanks for the help!  Github doesn't support attaching that file type.

**Comment by dswillett** [comment] 2021-11-10 21:42
See attached for most recent screenshots.  Tried to scale dask past three and it hung up and crashed just the server. 
<img width="628" alt="Screen Shot 2021-11-10 at 4 32 58 PM" src="https://user-images.githubusercontent.com/93540486/141198123-1e1014ad-a13c-4baf-94f8-0d2b5fc8754f.png">
<img width="692" alt="Screen Shot 2021-11-10 at 4 32 51 PM" src="https://user-images.githubusercontent.com/93540486/141198124-3917a154-a2af-4359-8fa6-580110999caa.png">

**Comment by dswillett** [comment] 2021-11-10 21:42
When we tried it with three users simultaneously, it brought the whole EKS cluster down.

**Comment by dswillett** [comment] 2021-11-10 21:43
To bring it back up, I reran qhub deploy.

**Comment by dswillett** [comment] 2021-11-10 21:47
> ☝️ Could we have more details on how it crashed? Was it just the dask cluster or the entire QHub? How did you bring it back up?

When we tried it with three users simultaneously, it brought the whole EKS cluster down. To bring it back up, I reran qhub deploy.

**Comment by dswillett** [comment] 2021-11-10 21:51
> Hey @dswillett, thank you for your interest in QHub, I'm sorry to hear that you're experiencing issues. I will try to recreate this issue as soon as I can. In the meantime, would you mind answering some of these questions:
> 
> * Can a single user launch dask workers? If so, how many at a single time?
> * Besides adding users and making minor changes to the `max_nodes`, are there any other changes that were made to the `qhub-config.yaml`? (it can be a little difficult to parse the config file when it's "[unformatted](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)" 😅)
> * Being able to run through [this dask example](https://gist.github.com/iameskild/1a45cbd114595fa371d2d127448c5e33) is a good sign that things are working, would you mind giving it a try as well?

To answer your questions:
 * A single user can launch dask workers.  After about 2-3 the server crashes.  If multiple users do it at the same time, the cluster comes down.  
 * I am pretty sure all config changes were minor.
 * The dask example you provided worked flawlessly.  

Hope this helps...

Could this be some sort of underlying constraint via AWS/EKS that it is not handling?

**Comment by iameskild** [comment] 2021-11-10 21:54
Thanks a lot @dswillett! I am starting my own QHub deployment on AWS (with your configuration settings) right now, I'll report back with any findings 👍

**Comment by dswillett** [comment] 2021-11-10 22:24
Thanks @iameskild! I am thinking it could be a cert issue potentially as well.  I am retrying lets encrypt to see if that solves it... Appreciate the effort on this!

**Comment by tylerpotts** [comment] 2021-11-10 23:38
@dswillett Is this a new AWS account? Do you know what the service quatas are for your vcpus? (see here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-resource-limits.html)

**Comment by iameskild** [comment] 2021-11-11 02:34
@dswillett here are notes from my recent troubleshooting:
- As an individual user launching dask-clusters, I do frequently encounter `server unavailable or reachable` messages, this is clearly something we need to investigate further but for the most part, other than being annoying, it didn't actually boot me from my jupyterlab session. 
- Besides the `server unavailable` issue described above, I can launch workers from multiple users at the same time without causing the EKS cluster to go down 
- I was surprised that you were able to get the `dask` environment built. When I tried, I kept getting an error (to check conda-store build logs, see `/home/conda/store/.logs`).
  - As an FYI, the [`qhub-dask`](https://github.com/conda-forge/qhub-dask-feedstock/blob/master/recipe/meta.yaml) package includes `dask`, `distributed` and `dask-gateway`   
- I also noticed that the `High Worker` can't be launched due to resource limitations, although it's memory guarantee is below what an [`m5.large` can accommodate](https://aws.amazon.com/ec2/instance-types/), there are other pods on that node which consume memory. If you want a larger worker, perhaps include the underlying instance type of the worker.
- Lastly, in general, only one node is needed for the `general` pool. I have seen instances in the past where dask-worker pods or jupyterlab pods find themselves on the `general` node and that can cause problems. I would recommend reducing that the `max_node: 1` for that node group. 

All of that is to say that I can't reproduce the EKS cluster failure issue but I definitely recognize the `server unavailable or unreachable` issue. If you wouldn't mind updating your `qhub-config.yaml` and trying to redeploy again. If you are still experiencing the EKS cluster going down, could you share the notebook you and others are running as well as any logs from that you might be able to capture from either the dask-worker pods, jupyterlab-user pods or any other troublesome pod; a tool like [k9s](https://k9scli.io/) is helpful in these situations.

**Comment by dharhas** [comment] 2021-11-11 02:38
@iameskild @costrouc is our log retriever thing working yet?

**Comment by iameskild** [comment] 2021-11-18 02:10
Hey @dswillett, have you had a chance to redeploy and test some of the proposals mentioned above? Let me know if this is still causing you issues. Thank you :)

**Comment by danlester** [comment] 2022-04-28 15:02
Closing for now, but please reopen if you have any further info and we will happily help, ideally using more recent qhub version.

**Closed by danlester** 2022-04-28 15:02 UTC
Labels: needs: more info, area: integration/Dask, needs: follow-up
