### ISSUE TITLE
Tuning Dask scheduler persistence [enhancement]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#970] opened 2021-12-14 16:25 UTC
## Description

Currently the dask auto-scheduler persists past a user's session.
+ The good: It is provides a robust experience for the typical usecase where the cluster is required for quite some time and does not need to be nursed by the user.
+ The bad: The worker pool will persist until the user kills it... this may be hard if they have since lost there kernel because time limits on inactivity for the user servers.
+ The ugly: A user can keep launching dask cluster as they learn the ropes with wild abandon. They have no feedback on the compute they have summoned that is now sitting idle.

**Comment by dharhas** [comment] 2022-01-11 16:57
Previously the Dask cluster was only live while the Jupyter notebook was active. This seems like a fairly critical issue to fix.

**Comment by dharhas** [comment] 2022-01-11 17:27
The short term fix might be to expose the idle-timeout as a config option with a reasonable default (i.e. 1 hr or 2 hrs):

https://gateway.dask.org/api-server.html#c.ClusterConfig.idle_timeout

**Comment by viniciusdc** [comment] 2022-01-11 17:30
> The short term fix might be to expose the idle-timeout as a config option with a reasonable default (i.e. 1 hr or 2 hrs):
> 
> https://gateway.dask.org/api-server.html#c.ClusterConfig.idle_timeout

I can expose that to the qhub-config, I will check if that can be do with override as well (this way we keep the pattern for customizations).

**Comment by iameskild** [comment] 2022-01-11 17:32
I think what we might want to look at is the `c.KubeController.completed_cluster_max_age` and determine why this value is not being respected.

https://gateway.dask.org/api-server.html#kubecontroller
https://github.com/Quansight/qhub/search?q=completedClusterMaxAge

**Comment by viniciusdc** [comment] 2022-01-11 17:33
@iameskild could you reproduce this again if possible? this might give uses clues about why the values are not being respected

**Comment by dharhas** [comment] 2022-01-11 17:41
> There's idle_timeout (https://gateway.dask.org/api-server.html#c.ClusterConfig.idle_timeout), a max time for the cluster to sit idle (unused) before it's culled

This can be set aggressively I think 15 or 30 mins is a good default, since this is for actual idle clusters that are not receiving tasks. If tasks are being received the cluster will stay alive.

This is probably related to the root cause:

https://github.com/dask/dask-gateway/issues/255

**Comment by viniciusdc** [comment] 2022-01-11 17:42
> > There's idle_timeout (https://gateway.dask.org/api-server.html#c.ClusterConfig.idle_timeout), a max time for the cluster to sit idle (unused) before it's culled
> 
> This can be set aggressively I think 15 or 30 mins is a good default, since this is for actual idle clusters that are not receiving tasks. If tasks are being received the cluster will stay alive.
> 
> This is probably related to the root cause:
> 
> [dask/dask-gateway#255](https://github.com/dask/dask-gateway/issues/255)

I see so it seems that they might have changed the default behavior of it then, we can then include the above specified `idle_timeout` to the [gateway config](https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/dask-gateway/templates/controller_config.py)

**Comment by dhirschfeld** [comment] 2022-01-12 00:09
> This can be set aggressively I think 15 or 30 mins is a good default

How about if you leave a computation running overnight and want to see the results in the morning?

**Comment by dharhas** [comment] 2022-01-13 03:54
In that case the scheduler shouldn't be idle, it should be sending/receiving tasks continuously through the long computation at least that is the way I read the docs. But it is worth experimenting with.

**Comment by dharhas** [comment] 2022-01-13 03:55
I also think you can override the idle time via the cluster options when you create the cluster. Again we should test.

**Comment by dharhas** [comment] 2022-01-13 03:58
Also if you were running an overnight computation, I would make the last step of the computation writing to disk or something else persistent so you could still see the results even if the cluster had been idle culled or your jlab kernel had died/got disconnected.

**Comment by dhirschfeld** [comment] 2022-01-13 04:06
> In that case the scheduler shouldn't be idle, it should be sending/receiving tasks continuously through the long computation.

But then the computation finishes at 3am and the scheduler will be idle until you access it in the morning.

Sure, you *should* save your results, but you might also want access to the entire state of the kernel, not just your results. If you know, then I guess you can always disable the timeout so it should at least be very clearly documented.

**Comment by costrouc** [comment] 2022-05-05 14:54
This should be fixed with idle culler in 0.4 release. Closing if this issue still exists.

**Closed by costrouc** 2022-05-05 14:54 UTC
Labels: type: enhancement, needs: discussion, area: integration/Dask
